## 6.3 Morphology
### 6.3.1 침식 연산
- 원래 있던 객체의 영역을 깍아내는 연산
- 연산을 위해 구조화요소 (getStructuringElement)라는 0, 1로 채워진 커널이 필요
- cv2.getStructuringElement(shape, ksize[, anchor])
    - shape : 구조화 요소 커널의 모양결정
        - cv2.MORPH_RECT : 사각형
        - cv2.MORPH_ELLIPSE : 타원형
        - cv2.MORPH_CROSS : 십자형
    - ksize : 커널 크기
    - anchor : 구조화 요소의 기준점, cv2.MORPH_CROSS에만 의미 있음(default : (-1, -1)) <br>
<br>
- dst = cv2.erode(src, kenel, [, anchor, iterations, borderType, borderValue])
    - kernel : 구조화 요소 커널 객체
    - anchor : cv2.getStructuringElement()와 동일
    - iterations : 침식 연산 적용 반복 횟수
    - borderType : 외곽 영역 보정 방법 설정 플래그
    - borderValue : 외곽 영역 보정 값

In [8]:
import cv2
import numpy as np

img = cv2.imread('img/morph_dot.png')

# 구조화 요소 커널, 사각형(3x3)
k = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))

# 침식 연산 적용
erosion = cv2.erode(img, k)

# result
merged = np.hstack((img, erosion))
cv2.imshow('Erode', merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 6.3.2 팽창 연산 (dilatation)
- 영상 속 사물의 주변을 덧붙여서 영역을 더 확장하는 연요
- 1로 채워진 영역이 온전히 덮이지 않으면 1로 채워넣음
- dst = cv2.dilate(src, kenel, [, anchor, iterations, borderType, borderValue])
    - 모든 인자는 cv2.erode()와 동일

In [5]:
import cv2
import numpy as np

img = cv2.imread('img/morph_hole.png')

# 구조화 요소 커널, 사각형(3x3)
k = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))

# 팽창 연산 적용
dst = cv2.dilate(img, k)

# result
merged = np.hstack((img, dst))
cv2.imshow('Dilate', merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 6.3.3 열림과 닫힘, 그밖의 모폴로지 연산
- 침식과 팽창은 어두운 부분의 점 노이즈를 없애는 데 효과적이지만, 원래의 모양이 변형
- 원래의 모양을 유지하며 노이즈만 제거하는 방법은 아래와 같음
    - 열림 = 침식 + 팽창
    - 닫힘 = 팽창 + 침식
    - gradient = 팽창 - 침식 (경계 검출과 비슷한 결과)
    - tophat = 원본 - 열림 (밝기 값이 크게 튀는 영역을 강조)
    - blackhat = 닫힘 - 원본 (어두운 부분 강조)
<br>
- 영상 속 사물의 주변을 덧붙여서 영역을 더 확장하는 연요
- 1로 채워진 영역이 온전히 덮이지 않으면 1로 채워넣음
- dst = cv2.morphologyEx(src, op, kenel, [, anchor, iteration, borderType, borderValue])
    - op : 모폴로지 연산 종류 지정
        - cv2.MORPH_OPEN : 열림 연산
        - cv2.MORPH_CLOSE : 닫힘 연산
        - cv2.MORPH_GRADIENT : 그레디언트 연산
        - cv2.MORPH_TOPHAT : 탑햇 연산
        - cv2.MORPH_BLACKHAT : 블랙햇 연산
    - kernel : 구조화 요소 커널
    - anchor : 커널의 기준점
    - iteration : 연산 반복 횟수
    - borderType : 외곽 영역 보정 방식
    - borderValue : 외곽 영역 보정 값

In [10]:
import cv2
import numpy as np

img1 = cv2.imread('img/morph_dot.png', cv2.IMREAD_GRAYSCALE)
img2 = cv2.imread('img/morph_hole.png', cv2.IMREAD_GRAYSCALE)

# 구조화 요소 커널, 사각형(5x5)
k = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))

# 열림 연산 적용
opening = cv2.morphologyEx(img1, cv2.MORPH_OPEN, k)

# 닫힘 연산 적용
closing = cv2.morphologyEx(img2, cv2.MORPH_CLOSE, k)

# result
merged1 = np.hstack((img1, opening))
merged2 = np.hstack((img2, closing))
merged = np.vstack((merged1, merged2))
cv2.imshow('opening, closing', merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
import cv2
import numpy as np

img = cv2.imread('img/morphological.png', cv2.IMREAD_GRAYSCALE)

# 구조화 요소 커널, 사각형(3x3)
k = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))

# 그레디언트 연산 적용
gradient = cv2.morphologyEx(img, cv2.MORPH_GRADIENT, k)

# result
merged = np.hstack((img, gradient))
cv2.imshow('gradient', merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
import cv2
import numpy as np

img = cv2.imread('img/moon_gray.jpg')

# 구조화 요소 커널, 사각형(9x9)
k = cv2.getStructuringElement(cv2.MORPH_RECT, (9, 9))

# tophat 연산 적용
tophat = cv2.morphologyEx(img, cv2.MORPH_TOPHAT, k)

# blackhat 연산 적용
blackhat = cv2.morphologyEx(img, cv2.MORPH_BLACKHAT, k)

# result
merged = np.hstack((img, tophat, blackhat))
cv2.imshow('tophat, blackhat', merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 6.4 이미지 피라미드
- 영상의 크기를 단계적으로 축소 또는 확대해서 피라미드처럼 쌓아 놓는 것

### 6.4.1 가우시안 피라미드
- pyrDown, pyrUp : 원본 영상의 크기를 1/4로 축소/확대
- dst = cv2.pyrDown(src, [, dst, dstsize, borderType])
- dst = cv2.pyrUp(src, [, dst, dstsize, borderType])
    - dstsize : 결과 영상 크기
    - borderType : 외곽 보정 방식

In [17]:
import cv2
import numpy as np

img = cv2.imread('img/girl.jpg')

# 가우시안 이미지 피라미드 축소
smaller = cv2.pyrDown(img)

# 가우시안 이미지 피라미드 확대
bigger = cv2.pyrUp(img)

# result
cv2.imshow('img', img)
cv2.imshow('pyrDown', smaller)
cv2.imshow('pyrUp', bigger)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 6.4.2 라플라시안 피라미드
- 크기 축소 및 확대 후에도 원본 복원이 필요한 경우 이용

In [19]:
import cv2
import numpy as np

img = cv2.imread('img/taekwonv1.jpg')

# 가우시안 이미지 피라미드 축소
smaller = cv2.pyrDown(img)

# 가우시안 이미지 피라미드 확대
bigger = cv2.pyrUp(smaller)

# 원본에서 확대한 영상 빼기
laplacian = cv2.subtract(img, bigger)
# 확대한 영상에 라플라시안 영상을 더해서 복원
restored = bigger + laplacian

# result
merged = np.hstack((img, laplacian, bigger, restored))
cv2.imshow('Laplacian Pyramid', merged)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 6.5 실전 워크숍
### 6.5.1 모자이크 처리2

In [21]:
import cv2

ksize = 30
win_title = 'mosaic'
img = cv2.imread('img/taekwonv1.jpg')

while True:
    x, y, w, h = cv2.selectROI(win_title, img, False)
    if x > 0 and h > 0:
        roi = img[y:y+h, x:x+w]
        roi = cv2.blur(roi, (ksize, ksize))
        img[y:y+h, x:x+w] = roi
        cv2.imshow(win_title, img)
    else:
        break
cv2.destroyAllWindows()

### 6.5.2 스케치 효과 카메라

In [29]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)
# cap = cv2.imread('img/yate.jpg')


if cap.isOpened(): 
    while True:
        # frame read
        ret, frame = cap.read()
        # 속도 향상을 위해 영상 크기를 절반으로 축소
        frame = cv2.resize(frame, None, fx=0.5, fy=0.5, interpolation=cv2.INTER_AREA)
        if cv2.waitKey(1) == 27: # esc 키로 종료
            break
        # to gray scale
        img_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        # 잡음 제거를 위해 가우시안 블러 필터 적용 (라플라시안 필터 적용 전 필수)
        img_gray = cv2.GaussianBlur(img_gray, (9, 9), 0)
        # 라플라시안 필터로 엣지 검출
        edges = cv2.Laplacian(img_gray, -1, None, 5)
        # 스레시홀드로 경계값만 남기고 제거하면서 화면 반전
        ret, sketch = cv2.threshold(edges, 70, 255, cv2.THRESH_BINARY_INV)

        # 경계선 강조를 위해 팽창 연산
        kernel = cv2.getStructuringElement(cv2.MORPH_CROSS, (3, 3))
        sketch = cv2.erode(sketch, kernel)

        # 경계선을 자연스럽게 하기위한 미디언 블러 필터 적용
        sketch = cv2.medianBlur(sketch, 5)
        # gray scale -> BGR scale
        img_sketch = cv2.cvtColor(sketch, cv2.COLOR_GRAY2BGR)

        # 컬러 이미지 선명선을 없애기 위해 평균 블러 필터 적용
        img_paint = cv2.blur(frame, (10, 10))
        # 컬러영상과 스케치 영상과 합성
        img_paint = cv2.bitwise_and(img_sketch, img_paint)

cap.release()
cv2.destroyAllWindows()

# Ch.7 영상 분할
## 7.1 컨투어
- 같은 색상이나 밝기의 연속된 점을 찾아 잇는 곡선을 찾아내면 모양 분석과 객체 인식에 사용할 수 있음
- cv2.findContours(src, mode, method, [, contours, hierarchy, offset])
    - mode : 컨투어 제공 방식
        - cv2.RETR_EXTERNAL : 가장 바깥쪽 라인만 제공
        - cv2.RETR_LIST : 모든 라인을 계층 없이 제공
        - cv2.RETR_CCOMP :  모든 라인을 2계층으로 제공
        - cv2.RETR_TREE : 모든 라인의 모든 계층 정보를 트리 구조로 제공
    - method : 근사 값 방식 선택
        - cv2.CHAIN_APPROX_NONE : 근사 계산하지 않고 모든 좌표 제공
        - cv2.CHAIN_APPROX_SIMPLE : 컨투어 꼭지점 좌표만 제공
        - cv2.CHAIN_APPROX_TC89_L1 : Tech-chin 알고리즘으로 좌표 개수 축소
        - cv2.CHAIN_APPROX_TC89_KC0S : Tech-chin 알고리즘으로 좌표 개수 축소
    - contours : 검출한 컨투어 좌표 (python list)
    - hierarchy : 컨투어 계층 정보
        - Next, Prev, FirstChild, Parent
            - -1: 해당 사항 없음
    - offset : ROI 등으로 인해 이동한 컨투어 좌표의 offset
<br>
- cv2.drawContours(img, contours, contourIdx, color, thickness)
    - contours : 그림 그릴 컨투어 배열
    - contourIdx : 그림 그릴 컨투어 index, -1 : 모든 컨투어 표시
    - color : 색상 값
    - thickness : 선 두께, 0: 채우기

In [34]:
import cv2
import numpy as np

img1 = cv2.imread('img/shapes.png')
img2 = img1.copy()

# to gray scale
img_gray = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
# 스레시홀드 바이너리 이미지로 만들어 검은 배경에 흰 전경으로 반전
ret, imthres = cv2.threshold(img_gray, 127, 255, cv2.THRESH_BINARY_INV)

# 가장 바깥쪽 컨투어에 대해 모든 좌표만 반환
contour, hierarchy = cv2.findContours(imthres, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

# 가장 바깥쪽 컨투어에 대해 꼭짓점 좌표만 반환
contour2, hierarchy = cv2.findContours(imthres, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# 각 컨투어의 개수 출력
print('도형의 개수: %d(%d)' % (len(contour), len(contour2)))

# 모든 좌표를 갖는 컨투어 그리기 (green)
cv2.drawContours(img1, contour, -1, (0, 255, 0), 4)
# 꼭지점 좌표만을 갖는 좌표를 갖는 컨투어 그리기 ('')
cv2.drawContours(img2, contour, -1, (0, 255, 0), 4)

# 컨투어의 모든 좌표를 작은 파란색 점(원)
for i in contour:
    for j in i:
        cv2.circle(img1, tuple(j[0]), 1, (255, 0, 0), -1)

# 컨투어의 모든 좌표를 작은 파란색 점(원)
for i in contour2:
    for j in i:
        cv2.circle(img2, tuple(j[0]), 1, (255, 0, 0), -1)

cv2.imshow('CHAIN_APPROX_NONE', img1)
cv2.imshow('CHAIN_APPROX_SIMPLE', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

도형의 개수: 3(3)


In [36]:
import cv2
import numpy as np

img1 = cv2.imread('img/shapes_donut.png')
img2 = img1.copy()

# to gray scale
img_gray = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
# 스레시홀드 바이너리 이미지로 만들어 검은 배경에 흰 전경으로 반전
ret, imthres = cv2.threshold(img_gray, 127, 255, cv2.THRESH_BINARY_INV)

# 가장 바깥쪽 컨투어에 대해 모든 좌표만 반환
contour, hierarchy = cv2.findContours(imthres, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
# 컨투어 개수와 계층 트리 출력
print(len(contour), hierarchy)

# 모든 컨투어를 트리 계층으로 수집
contour2, hierarchy = cv2.findContours(imthres, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
# 컨투어 개수와 계층 트리 출력
print(len(contour2), hierarchy)


# 모든 좌표를 갖는 컨투어 그리기 (green)
cv2.drawContours(img1, contour, -1, (0, 255, 0), 3)

for idx, cont in enumerate(contour2):
    # extract random color
    color = [int(i) for i in np.random.randint(0, 255, 3)]
    # contour index 마다 랜덤한 색상으로 그리기
    cv2.drawContours(img2, contour2, idx, color, 3)
    # 컨투어 첫 좌표에 인덱스 숫자 표시
    cv2.putText(img2, str(idx), tuple(cont[0][0]), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 255))

cv2.imshow('RETR_EXTERNAL', img1)
cv2.imshow('RETR_TREE', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

3 [[[ 1 -1 -1 -1]
  [ 2  0 -1 -1]
  [-1  1 -1 -1]]]
6 [[[ 2 -1  1 -1]
  [-1 -1 -1  0]
  [ 4  0  3 -1]
  [-1 -1 -1  2]
  [-1  2  5 -1]
  [-1 -1 -1  4]]]


### 7.1.1 이미지 모멘트와 컨투어 속성
- 모멘트 : 영상에서는 대상 물체의 양적인 속성을 표현할 때 사용
- m_p,q = Sigma_x(Sigma_y(f(x, y)*(x - xc)^p*(y -yc)^q))
- xc = m10/m00, yc = m01/m00
- 중심 모멘트를 정규화 할 시에 크기가 변해도 같은 값을 얻고 식은 아래와 같음
- nu_p,q = m_p,q/m00^((p + q)/2 + 1)
- moment = cv2.moments(contour)
    - contour : 모멘트 계산 대상 컨투어 좌표
    - moment : 결과 모멘트 (python dictionary)
        - m00, m01, m10, m11, m02, m12, m20, m21, m03, m30: 공간 모멘트
        - mu20, mu11, mu02, mu30, mu21, mu12, mu03 : 중심 모멘트
        - nu20, nu11, nu02, nu30, nu21, nu03 : 정규화 중심 모멘트
- retval = cv2.contourArea(contour[, oriented=False])
    - contour : 넓이를 계산할 컨투어
    - oriented : 컨투어 방향 플래그
        - True : 컨투어 방향에 따라 음수 반환
        - False : 절대값 반환
    - retval : 컨투어 영역의 넓이 값
- retval = cv2.arcLength(curve, closed)
    - curve : 둘레를 계산할 컨투어
    - closed : 닫힌 호인지 여부 플래그
    - retval : 컨투어 영역의 둘레 값

In [39]:
import cv2
import numpy as np

img = cv2.imread('img/shapes.png')

# to gray scale
img_gray = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
# 스레시홀드 바이너리 이미지로 만들어 검은 배경에 흰 전경으로 반전
ret, imthres = cv2.threshold(img_gray, 127, 255, cv2.THRESH_BINARY_INV)

# 가장 바깥쪽 컨투어에 대해 모든 좌표만 반환
contours, hierarchy = cv2.findContours(imthres, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

for c in contours:
    # calculate moment
    mmt = cv2.moments(c)
    # m10/m00, m01/m00, calculate center point
    cx = int(mmt['m10']/mmt['m00'])
    cy = int(mmt['m01']/mmt['m00'])
    
    # 넓이
    a = mmt['m00']

    # 외각선 길이
    l = cv2.arcLength(c, True)

    # center pt.에 노란색 점 그리기
    cv2.circle(img, (cx, cy), 5, (0, 255, 255), -1)
    # 중심점 근처에 넓이 그리기
    cv2.putText(img, 'A: %.0f' %a, (cx, cy+20), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 255))

    # 컨투어 시작점에 길이 그리기
    cv2.putText(img, 'L: %.2f' %l, tuple(c[0][0]), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 255))

    # 각 컨투어의 개수 출력
    print('area : %.2f' %cv2.contourArea(c, False))

cv2.imshow('Center', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

area : 9870.00
area : 12544.00
area : 6216.00


- x, y, w, h = cv2.boundingRect(contour) : 좌표를 감싸는 사각형 구하기
    - x, y : 사각형의 왼쪽 상단 좌표
    - w, h : 폭, 높이
- rotateRect = cv2.minAreaRect(contour) : 좌표를 감싸는 최소한의 사각형 계산
    - rotateRect : 회전한 사각형 좌표
        - center (x, y) / size (w, h) / angle : 회전 각 (양수: 시계 / 음수: 반시계)
- vertex = cv2.boxPoints(rotateRect) : rotateRect로 부터 꼭지점 좌표 계산
- center, radius = cv2.minEnclosingCircle(contour) : 좌표 감싸는 최소한의 동그라미
- area, triangle = cv2.minEnclosingTriangle(points) : : 좌표 감싸는 최소한의 삼각형
- ellipse = cv2.fitEllipse(points) : 좌표 감싸는 최소한의 타원
- line = cv2.fitLine(points, distType, param, reps, aeps[, line]) : 중심점을 통과하는 직선계산
    - distType : 거리계산 방식
        - cv2.DIST_L2, cv2.DIST_L1, cv2.DIST_L12, cv2.DIST_FAIR, cv2.DIST_WELSCH, cv2.DIST_HUBER
    - param : distType에 전달할 인자, 0 = 최적값 선택
    - reps : 반지름 정확도, 선과 원본 좌표의 거리, 0.01 권장
    - aeps : 각도 정확도, 0.01 권장
    - line
        - vx, vy : 정규화된 단위 벡터, vy/vx: 직선의 기울기 (tuple)
        - x0, y0 : 중심점 좌표 (tuple)

In [61]:
import cv2
import numpy as np

img = cv2.imread('img/lightning.png')

# to gray scale
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# 스레시홀드 바이너리 이미지로 만들어 검은 배경에 흰 전경으로 반전
ret, imthres = cv2.threshold(img_gray, 127, 255, cv2.THRESH_BINARY_INV)

# 가장 바깥쪽 컨투어에 대해 모든 좌표만 반환
contours, hierarchy = cv2.findContours(imthres, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

contr = contours[0]

# 감싸는 사각형 표시 (검정)
x, y, w, h = cv2.boundingRect(contr)
cv2.rectangle(img, (x, y), (x+w, y+h), (0, 0, 0), 3)

# 최소한의 사각형 표시 (초록)
rect = cv2.minAreaRect(contr)
box = cv2.boxPoints(rect) # 중심점과 각도를 4개의 꼭짓점 좌표로 변환
box = np.int0(box) # 정수로 변환
cv2.drawContours(img, [box], -1, (0, 255, 0), 3)

# 최소한의 원 (파랑)
(x, y), radius = cv2.minEnclosingCircle(contr)
cv2.circle(img, (int(x), int(y)), int(radius), (255, 0, 0), 2)

# 최소한의 삼각형 (분홍)
ret, tri = cv2.minEnclosingTriangle(contr)
cv2.polylines(img, [np.int32(tri)], True, (255, 0, 255), 2)

# 최소한의 타원 (노랑)
ellipse = cv2.fitEllipse(contr)
cv2.ellipse(img, ellipse, (0, 255, 255), 3)


# 중심점을 통과하는 직선 표시 (red)
[vx, vy, x, y] = cv2.fitLine(contr, cv2.DIST_L2, 0, 0.01, 0.01)
cols, rows = img.shape[0], img.shape[1]
cv2.line(img, (0, int(0-x*(vy/vx)+y)), (cols-1, int((cols-x)*(vy/vx) + y)), (0, 0, 255), 2)

cv2.imshow('Bound Fit shapes', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
# (0, float(0-x*(vy/vx)+y))